### ISSUE TITLE
Can't add custom span traces with dynamic values

### ISSUE THREAD

**Issue by fsanchezgl** [DataDog/kong-plugin-ddtrace#21]
The configuration allows to add custom span tags, with static values. 
For reference, the JS DD-tracer plugin allows me add custom spans tags to tracer.
I would like to include custom trace spans without modifying the provided DDtracer plugin

**Comment by dgoffredo** [comment]
Hi, Francisco. You refer to "custom trace spans," but based on your [proposed feature](https://github.com/DataDog/kong-plugin-ddtrace/pull/22/files), what you want are "custom span tags."

A _span_ is a period of time over which an operation occurs (such as processing a request). A span can have zero or more _tags_, which are key/value pairs of strings.

A _trace_ is a collection of spans that share the same _trace ID_, where the spans most likely form a tree due to the parent-child relationship that can exist between two spans.

Other Datadog tracers, such as Python's [dd-trace-py][1], support a `DD_TAGS` environment variable that allows custom tags to be added to spans in the manner you've proposed. There is also [DD_TRACE_HEADER_TAGS][2], allowing such tags to be deduced from incoming request headers.

I'll discuss with the team how best to support the feature you've requested. I suspect there's "the Kong way," and "the Datadog way," and perhaps "the NGINX way." People are on holiday this time of year, so likely we'll revisit this is January 2024.

Thanks for your contribution.

[1]: https://ddtrace.readthedocs.io/en/stable/configuration.html#DD_TAGS
[2]: https://ddtrace.readthedocs.io/en/stable/configuration.html#DD_TRACE_HEADER_TAGS

**Comment by dmehala** [comment]
Hi @fsanchezgl 

Thank you for reporting this issue. I wanted to inform you that we recently merged the fix in https://github.com/DataDog/kong-plugin-ddtrace/pull/28. This solution should address the problem you raised, and it will be included in the upcoming release.
